dist: xenial
language: python
env:
  global:
    secure: OG7AhLPzIwNVmjA+6ngzzUdlp8vX0A6oofZj1N650DwIQKExJlIitKmhMrlA7eIbiwDhiWPdZjq5UMeRwSS3TqfA1IwBUXvtsFdmyHJRasidRj89zyruqszrAetjyVBpRzfhR1m8NV02gvLtbJQDLdnEUkAhG1rSASikBmxOpGKx2cS7uta9MUjqANWVsCr0/76tYiP7m3yfFGEO6vJUj1ObmAsDZmQiOLB/xM9xZxTcd6FnyD/NkNcaQ3hriL+Xev9X/5PhcV+XUXrNC+NlsaEXECCvu2PkRvUUitCcpgN5HWmR+LTLcHSAU+ro/JSLsd5PcL0Ve8DW4OTp5BWn5SD9XivONSSN3R1j+lg3s75qWyftIDtUyW6VbAS/NUVoHdbZc9k3DP7mMPYavr7+uQ8Gd5PL/aDsJnmvmmAY0h24KzwS+IoZIgbD/LKXTq6IccUj5cr+srX7u2YmGVa/ZTQ5cNo9rZFgZkl0X+KFHtz8i4gFLcpCXu/wBc5MfgNOxhsSgkCJWNcTG+eTug8dq1UhqxOxu9S2Dvc4tqA8vK74TZOp9h1J2DTfFI4hEi3O2VXK3LCzblAvwVFtqEG9dcowCojN54AfOMzdDew+brxkkIS6Sy1mPllV872/7f/a9xnjl8h7moZxZ5cLsDGZMyKF67oZ0RXrlTLcct3gyHA=

matrix:
  include:
    - python: '3.6'
      env: NOXSESSION=tests-3.6
    - python: '3.7'
      env: NOXSESSION=tests-3.7
    - python: '3.8'
      env: NOXSESSION=tests-3.8
    - python: '3.8'
      env: NOXSESSION=lint
    - python: '3.8'
      env: NOXSESSION=docs

install: pip install -U pip setuptools nox

script: nox -s $NOXSESSION

deploy:
  provider: script
  script: nox -s deploy
  on:
    tags: true
    branch: master
    repo: click-contrib/click_params
    condition: "$NOXSESSION = tests-3.8"
