dist: xenial
language: python
env:
  global:
    - secure: t9Un8HHUW0R5dzkuhS9c1wjaSXYJ5vE3kRep//Q737Ajc53VMmjHR7lXSG57JSY3jCRtq8Qxio4C1/eZiG/qZeQAJy/R1vziqV1NAB2JWR498Y1cqTy3ZMXH0Z+vbubPHUS3gfPT0wxPffab6/5FYIq+QIvOaf4Yj0AbK/q954Y7cNpLxi3tziZy+OLnFU4xTs1eLsl7qyaendGdNB5SeZCnI4l+Siv7pElHSwNJUMlom8/aWU1GISpj4bOKyd7u7bIrKtmqTXcUpWADNlXE+SU010SVdOvM/DQRRbRsnwfoF09vzqF8ooSnWA9oIudS+F3fgc/G0v+oJS6suOCi1eZBqQzb/3MLvWKXAs7TugBo5Sl/QjUryvmdBqg9tzy6la2fEoF6m7nvi1HpoCOzbklZcdH2cxj2dEhFKXfy7NMBa7RiPk9rC9+YtGiqetywVVZRq7NdfY4jjqYQ9v1RtVFGteCbwip01j1GkXjZOCs+2kz1NBN+O/OAUSJu1CcZlzskQXgGSEagqAaUBW8O5+wWJESpx/O8nQogkypUJSUbw65CaXXcR6LtU5aYs+4pSbHk1QOuoNapd2UjILkwSRQfPptF1WZVvfEdI9Rzu3EVbPy5HpiqBJiiHs7gvD7r3hTW+JBEPLXUbzjdx7QJ6N2HaT6/exfCdUNUx9/lfnE=

matrix:
  include:
    - python: '3.6'
      env: NOXSESSION=tests-3.6
    - python: '3.7'
      env: NOXSESSION=tests-3.7
    - python: '3.8'
      env: NOXSESSION=tests-3.8
    - python: '3.8'
      env: NOXSESSION=lint
    - python: '3.8'
      env: NOXSESSION=docs

install: pip install -U pip setuptools nox

script: nox -s $NOXSESSION

deploy:
  provider: script
  script: nox -s deploy
  on:
    tags: true
    branch: master
    repo: click-contrib/click_params
    condition: "$NOXSESSION = tests-3.8"
